// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:web:8b5c8d9e0f1a2b3c4d5e6f7',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    authDomain: 'gespay-27b63.firebaseapp.com',
    storageBucket: 'gespay-27b63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:android:b40018e08e26d27bb23021',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    storageBucket: 'gespay-27b63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:ios:8b5c8d9e0f1a2b3c4d5e6f7',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    storageBucket: 'gespay-27b63.firebasestorage.app',
    iosBundleId: 'com.example.flutter_aplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:ios:8b5c8d9e0f1a2b3c4d5e6f7',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    storageBucket: 'gespay-27b63.firebasestorage.app',
    iosBundleId: 'com.example.flutter_aplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:web:8b5c8d9e0f1a2b3c4d5e6f7',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    authDomain: 'gespay-27b63.firebaseapp.com',
    storageBucket: 'gespay-27b63.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCYHYkg-2LWIwcvcaEG-hsNeGKfZepMGm0',
    appId: '1:1030128422260:web:8b5c8d9e0f1a2b3c4d5e6f7',
    messagingSenderId: '1030128422260',
    projectId: 'gespay-27b63',
    authDomain: 'gespay-27b63.firebaseapp.com',
    storageBucket: 'gespay-27b63.firebasestorage.app',
  );
}
